name: Copy Image to Aliyun
on:
  push:
    branches: [ main ]

jobs:
  copy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install skopeo
        run: sudo apt update && sudo apt install -y skopeo

      - name: Login to Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: dachangren
          password: Qwe!234567
          logout: false

      - name: Copy OpenMetadata Image
        run: |
          skopeo copy docker://openmetadata/openmetadata:1.12.6 docker://registry.cn-hangzhou.aliyuncs.com/dachang_ren/openmetadata:1.12.6
